const WindowConstants = {

  WINDOW_RESIZE: 'WINDOW_RESIZE',
  WINDOW_ON_FOCUS: 'WINDOW_ON_FOCUS',
  WINDOW_ON_BLUR: 'WINDOW_ON_BLUR',
  WINDOW_ON_MOUSEMOVE: 'WINDOW_ON_MOUSEMOVE',

  MOUSE_MOVE: 'MOUSE_MOVE',
  MOUSE_DOWN: 'MOUSE_DOWN',
  MOUSE_UP: 'MOUSE_UP',

  LANDSCAPE: 'LANDSCAPE',
  PORTRAIT: 'PORTRAIT'

}

export default WindowConstants
